[package]
name = "grid-vis"
version = "0.1.0"
authors = ["taotao54321 <taotao54321@gmail.com>"]
edition = "2018"

[dependencies]
eyre = "0.6.5"
image = "0.23.14"
imageproc = "0.22.0"
itertools = "0.10.0"
once_cell = "1.7.2"
rusttype = "0.9.2"
